# Copyright: (c) 2021, Michal Mocnak <michal@narra.eu>, Eric Rosenzveig <eric@narra.eu>
# Copyright: (c) 2021, Narra Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

development:
  clients:
    default:
      database: narra_dev
      hosts:
        - mongo:27017
      options:
        max_pool_size: 10
  options:
    background_indexing: true
    belongs_to_required_by_default: false
    preload_models: true
    raise_not_found_error: false

production:
  clients:
    default:
      database: narra
      hosts:
        - mongo:27017
      options:
        max_pool_size: 10
  options:
    background_indexing: true
    belongs_to_required_by_default: false
    preload_models: true
    raise_not_found_error: false

test:
  clients:
    default:
      database: narra_test
      hosts:
        - localhost:27017
      options:
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
      preload_models: true
      raise_not_found_error: false
